# This file is auto-generated from colors.json and fonts.json. Do not edit directly.
# Generated by generate_theme.R based on LoQE Brand Guidelines v1.1

#----------------------------------------------------------#
# LoQE Brand Compliant R Theme Settings
#----------------------------------------------------------#

# Load required packages for theme
if (!require("ggplot2")) stop("ggplot2 package is required")
if (!require("sysfonts")) stop("sysfonts package is required for custom fonts")
if (!require("showtext")) stop("showtext package is required for custom fonts")

# Load Google Fonts using sysfonts with error handling
# Try to load Plus Jakarta Sans (may be named differently in Google Fonts)
tryCatch({
  sysfonts::font_add_google("Plus Jakarta Sans", "loqe_body")
}, error = function(e) {
  # Try alternative names for Plus Jakarta Sans
  tryCatch({
    sysfonts::font_add_google("Jakarta Sans", "loqe_body")
  }, error = function(e2) {
    # Fallback to a similar font
    message("Plus Jakarta Sans not found, using Inter as fallback")
    sysfonts::font_add_google("Inter", "loqe_body")
  })
})

# Load Space Grotesk
tryCatch({
  sysfonts::font_add_google("Space Grotesk", "loqe_heading")
}, error = function(e) {
  message("Space Grotesk not found, using Roboto Condensed as fallback")
  sysfonts::font_add_google("Roboto Condensed", "loqe_heading")
})

# Load JetBrains Mono
tryCatch({
  sysfonts::font_add_google("JetBrains Mono", "loqe_mono")
}, error = function(e) {
  message("JetBrains Mono not found, using Fira Code as fallback")
  sysfonts::font_add_google("Fira Code", "loqe_mono")
})

# Enable showtext for rendering custom fonts
showtext::showtext_auto()

# LoQE Brand Colors (from brand guidelines)
loqe_cols <- c(
  black = "#1F2937",
  white = "#F2F4F2",
  teal = "#00857E",
  pistachio = "#87BF79",
  seal_brown = "#641F03",
  dark_green = "#002A28",
  fulvous = "#D47F14"
)

# LoQE Color Scales for ggplot2
scale_colour_loqe <- function(...) ggplot2::scale_colour_manual(values = loqe_cols, ...)
scale_fill_loqe <- function(...) ggplot2::scale_fill_manual(values = loqe_cols, ...)

# Primary color sequence (for ordered data)
loqe_primary_sequence <- c("#00857E", "#87BF79", "#641F03")

# Diverging color palette (for diverging data)
loqe_diverging <- c("#002A28", "#F2F4F2", "#D47F14")

# Text and background colors
loqe_text_color <- "#1F2937"
loqe_background_color <- "#F2F4F2"
loqe_accent_color <- "#D47F14"

# Define typography (based on LoQE brand guidelines)
# Using registered font names from sysfonts
loqe_base_font <- "loqe_body"
loqe_heading_font <- "loqe_heading"
loqe_mono_font <- "loqe_mono"

# Define text sizes (following brand hierarchy from fonts.json)
# Convert px to pt: 1px ≈ 0.75pt (at 96 DPI)
text_size_main_px <- 30
text_size_main_pt <- text_size_main_px * 0.75  # Convert px to pt
text_size_small <- text_size_main_pt * 0.8
text_size_base <- text_size_main_pt * 0.9
text_size_medium <- text_size_main_pt * 1.0
text_size_large <- text_size_main_pt * 1.2
text_size_xlarge <- text_size_main_pt * 1.4

# Define line sizes
line_size_thin <- 0.25
line_size_base <- 0.5
line_size_thick <- 1.0

# Define output dimensions (standard sizes)
image_width <- 16
image_height <- 12
image_units <- "cm"
image_dpi <- 300

# Create LoQE-compliant ggplot2 theme
theme_loqe <- function(base_size = text_size_base,
                       base_family = loqe_base_font,
                       base_line_size = line_size_base,
                       base_rect_size = line_size_base) {
  ggplot2::theme_bw(base_size = base_size,
                   base_family = base_family,
                   base_line_size = base_line_size,
                   base_rect_size = base_rect_size) +
  ggplot2::theme(
    # Text elements
    text = ggplot2::element_text(family = loqe_base_font, colour = "#1F2937"),
    plot.title = ggplot2::element_text(family = loqe_heading_font, colour = "#002A28", face = "bold", size = ggplot2::rel(1.4)),
    plot.subtitle = ggplot2::element_text(family = loqe_base_font, colour = "#1F2937", size = ggplot2::rel(1.1)),
    axis.title = ggplot2::element_text(family = loqe_base_font, colour = "#1F2937", size = ggplot2::rel(1)),
    axis.text = ggplot2::element_text(family = loqe_base_font, colour = "#1F2937", size = ggplot2::rel(0.9)),
    legend.title = ggplot2::element_text(family = loqe_base_font, colour = "#1F2937", size = ggplot2::rel(1)),
    legend.text = ggplot2::element_text(family = loqe_base_font, colour = "#1F2937", size = ggplot2::rel(0.9)),
    strip.text = ggplot2::element_text(family = loqe_heading_font, colour = "#002A28", face = "bold"),
    
    # Background elements
    plot.background = ggplot2::element_rect(fill = "#F2F4F2", colour = NA),
    panel.background = ggplot2::element_rect(fill = "#F2F4F2", colour = NA),
    legend.background = ggplot2::element_blank(),
    legend.key = ggplot2::element_blank()
  )
}

# Set the default ggplot2 theme to LoQE theme
ggplot2::theme_set(theme_loqe())

# Helper functions for common LoQE visualizations
loqe_discrete_colors <- function(n) {
  if (n <= length(loqe_cols)) {
    return(loqe_cols[1:n])
  } else {
    # Generate more colors using colorRampPalette if needed
    return(colorRampPalette(loqe_cols)(n))
  }
}

# Export commonly used values for backward compatibility
text_size <- text_size_base
line_size <- line_size_base
